name: country_flags_pro
description: "Flutter package project by Sanjarbek Fayzullayev"
version: 0.0.6
homepage: https://t.me/sanjarbekfayz
repository: https://github.com/SanjarbekFayzullayev/country_flags_pro

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/svg/
